version: "2"

services:
  gondolin-server:
    image: quay.io/setuinfra/gondolin:<tag>
    #restart: on-failure:5
    #mem_limit: 512m
    environment:
      # Switch server credentials
      - HTTP_PROXY=http://<user>:<password>@<switch-server>.setu.co:<port>
      - ALL_PROXY=http://<user>:<password>@<switch-server>.setu.co:<port>
      # Application config
      - APPLICATION_HOST=0.0.0.0
      - APPLICATION_PORT=3000
      - LOG_IN_FILE=nope
      # Axis config
      - END_POINT=<axis-endpoint>
    command: /app/server
    ports:
      - 3000:3000
